from uuid import UUID

from fastapi import HTTPException, status
from sqlalchemy import select, text
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.orm import Session

from app.models.product import Product
from app.schemas.product import ProductCreate, ProductUpdate


SKU_PREFIX = "PROD"
SKU_PADDING = 6


def generate_product_sku(db: Session) -> str:
    """Generate a deterministic, human-readable SKU."""
    db.execute(text("CREATE SEQUENCE IF NOT EXISTS product_sku_seq START WITH 1 INCREMENT BY 1"))
    next_value = db.execute(text("SELECT nextval('product_sku_seq')")).scalar_one()
    return f"{SKU_PREFIX}-{int(next_value):0{SKU_PADDING}d}"


def create_product(db: Session, payload: ProductCreate) -> Product:
    """Create and persist a product with an autogenerated SKU."""
    for _ in range(3):
        product = Product(
            name=payload.name,
            sku=generate_product_sku(db),
            price=payload.price,
            stock_quantity=payload.stock_quantity,
        )
        db.add(product)
        try:
            db.commit()
            db.refresh(product)
            return product
        except IntegrityError:
            db.rollback()
            # Retry on duplicate SKU race or manual data conflicts.
            continue
        except SQLAlchemyError as exc:
            db.rollback()
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Unexpected server error",
            ) from exc

    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="Unable to generate unique SKU",
    )


def get_products(db: Session, skip: int = 0, limit: int = 10) -> list[Product]:
    """Fetch products with pagination."""
    statement = select(Product).order_by(Product.created_at.desc(), Product.id).offset(skip).limit(limit)
    return list(db.scalars(statement).all())


def get_product_by_id(db: Session, product_id: UUID) -> Product:
    """Fetch a single product by id or raise 404."""
    product = db.scalar(select(Product).where(Product.id == product_id))
    if product is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")
    return product


def update_product(db: Session, product_id: UUID, payload: ProductUpdate) -> Product:
    """Update mutable product fields."""
    product = get_product_by_id(db, product_id)
    update_data = payload.model_dump(exclude_unset=True)

    if "name" in update_data and isinstance(update_data["name"], str):
        update_data["name"] = update_data["name"].strip()
        if not update_data["name"]:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Product name cannot be empty",
            )

    for field_name, field_value in update_data.items():
        setattr(product, field_name, field_value)

    try:
        db.commit()
        db.refresh(product)
    except SQLAlchemyError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unexpected server error",
        ) from exc

    return product


def delete_product(db: Session, product_id: UUID) -> None:
    """Delete a product by id."""
    product = get_product_by_id(db, product_id)
    try:
        db.delete(product)
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Product has existing orders",
        ) from exc
    except SQLAlchemyError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unexpected server error",
        ) from exc
